name: Continuous integration workflow

on:
  pull_request:
    branches: [ "main" ]

env:
  GO_VERSION: 1.22.5

jobs:
  run-linters:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{env.GO_VERSION}}

    - name: Run linters
      uses: golangci/golangci-lint-action@v6.0.1
      with:
        version: latest

  audit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{env.GO_VERSION}}

    - name: Download dependencies
      run: go mod download

    - name: Verify dependencies
      run: go mod verify

    - name: Install Goose 
      run: go install -tags="no_clickhouse no_libsql no_mssql no_mysql no_postgres no_vertica no_ydb" github.com/pressly/goose/v3/cmd/goose@latest

    - name: Set up migration
      run: make migration-up

    - name: Check building process of the project
      run: make check-build
      env:
        CGO_ENABLED: 1

    - name: Run tests
      run: make test