name: Continuous integration workflow

on:
  pull_request:
    branches: [ "main" ]

env:
  GO_VERSION: 1.22.5

jobs:
  run-linters:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{env.GO_VERSION}}

    - name: Run linters
      uses: golangci/golangci-lint-action@v6.0.1
      with:
        version: latest

  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{env.GO_VERSION}}

    - name: Verify dependencies
      run: go mod verify

    - name: Build the project
      run: go build -v ./...

    - name: Run tests
      run: go test -v ./...